### ISSUE TITLE
API endpoint for new work

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#115]
Accepts json hash of properties, including metadata, file memberships, and permissions, suitable for creating a complete, publishable work in Scholarsphere. Incomplete metadata, or other errors would return a 422 error, otherwise 201 success response.

## Blocks

Blocked by #37 and #116 

## TODO

- [x] Direct upload endpoint #108 
- [x] Investigate multipart upload process for API #114
- [x] Enable multipart upload with new works #172
