### ISSUE TITLE
Implement ACLs

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#116]
Tables exist, they need to be filled with data. ACLs only apply to Works and not versions, therefore any version of a work has the same permissions as the rest of the versions of that work.

## TODO

- [x] define a set of levels for our ACLs and state what actions those levels explicitly allow #133
- [x] implement visibility-based, application-wide groups such as "public" and "registered" for public access and PSU-only access respectively #132  
- [x] create a permissions object or module that contains a set of methods for managing all the permissions associated with a given work #135 
- [x] set visibility for published works #146 
- [x] index ACLs and use Blacklight access controls gem to enforce them in search results #128 
- [x] create "badges" to display the visibility levels of works in the UI #152 
- [x] ~~enforce ACLs when viewing individual records in Solr~~ #129
- [x] updated existing policies to enforce ACLs for non-Solr based displays #130
- [x] write default ACLs to works upon creation, i.e. depositor has edit access #131
- [ ] ~~build UI for adding additional user and group access to works~~ #134 

## Questions

@srerickson should weigh in on these ⚓️ 

* should the dashboard display work versions that I do not _own_ but have edit or read access to?
* do we need a separate table for groups if we need to index their ids as FKs and add additional application-level groups (ex. "public")? _Yes_, see #37 
* does the absence of any groups or users mean _no access_ (the restrictive model) or should it mean _all access_ (the permissive model)? _It means no access_
* can we edit permissions/ACLs without creating a new work version? _yes_
* do we want to track changes in permissions like we do metadata? _no_
