### ISSUE TITLE
WorkVersion's published_date is a singular field and validated

### ISSUE THREAD

**Issue by rschenk** [psu-stewardship/scholarsphere-4#140]
`WorkVersion#published_date` is currently a multi-value field. We agreed in #101 that [it should be singular](https://github.com/psu-stewardship/scholarsphere-4/issues/101#issuecomment-566184244).

### Todo
- [x] Determine how many legacy ScholarSphere works have multiple values in this field.
- [x] Figure out how we're going to reduce those multiple values into a single one when we port the data over
- [x] Make `WorkVersion#published_date` a singular field

### Bonus Todo?
- [x] Enforce a standard format for storing dates as strings (date-picker on UI?). @srerickson suggests ISO8601, but will this handle every scenario we need to address?
- [x] Validate that `published_date` is both present and in the correct format when a WorkVersion is published
- [x] Ensure that the Solr document/indexer can properly "explode" an imprecise date out into a date range, e.g. "2019" becomes "2019-01-01 00:00:00" - "2019-12-31 23:59:59" (Ryan did this in CHO for EDTF dates. Yoink that code?)

### Open Questions
1. Does ISO8601 cover all the use cases that we have?

**Comment by awead** [comment]
## WDLL

* make `published_date` a singular field
* validate field as an ETDF-type date field
* incorrect or non-EDTF dates will save but prevent the record's publish action
* index `published_date` into  Solr as an "exploded" date range (like we did in CHO)
* for migration, multiple values will be concatenated and the resulting record will remain in draft status until fixed

## Remaining Questions
1. Is `published_date` required for publishing?
2. Do we want a datepicker or just leave it as a text field?
