### ISSUE TITLE
Implement creators and aliases

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#149]
Aliases are multiple variations of the same creator. A work will have one or more creators, and each of those creators can have multiple aliases. Users can assign creators to works using their aliases, as well as enter new creators, for example, when collaborating with people from other institutions.

## Features

* changes to an alias should create a new alias tied to the same creator
* users may update/add new aliases to existing creators
* a work's metadata will have the depositor as the creator, with the metadata auto-populated from LDAP
* users may not alter the creator record once it has been saved (for now)
* new creators may be added during the work version edit step
* new creators may come from LDAP or be entered manually, such as a non-PSU individual
* works are searchable by both creator and alias
* facets use the creator canonical name only

## TODO

- [x] Move alias association from work to work version #176
- [x] Add new creator/alias combinations to the edit form #179
- [x] Send creator/alias and orcids to datacite #186 
- [x] Index creators and aliases into Solr #178
- [x] Search existing creators both via LDAP and locally added creators #180
- [x] Interactive UI for searching and adding creators #244
- [x] Creators/aliases are included in Work History #195 
- [x] Creators/aliases are included in diffs between versions #202

**Comment by DanCoughlin** [comment]
@awead can give @monksp a quick tour of how this works in current ScholarSphere

**Comment by awead** [comment]
Closed in #523
