### ISSUE TITLE
Move alias association from work to work version

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#176]
Moves the AR association between aliases and works, to aliases and work versions. 

## TODO
* [x] make the changes in Work, WorkVersion, and WorkCreation
* [x] rename WorkCreation to WorkVersionCreation
* [x] changeup the datamodel: remove the alias table and add the alias string field to WorkVersionCreation
* [x] update factories to create works with generated creators using the Faker gem
* [x] update BuildNewWorkVersion to copy over existing alias/creators from the old version to the new
