### ISSUE TITLE
Mapping metadata fields from GenericWork to Work and WorkVersion

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#193]
Scholarsphere 3's work model, GenericWork, has fields that need mapping to new or existing fields in our Work/WorkVersion models. We will need to determine which fields should be added and what data transformations should take place when migrating the data over. These fields include:
* `resource_type`, dropdown selection
* `date_created`, aka. "Published Date" which is a user-entered, multi-valued string, and multiple values do exist
* `date_uploaded`, Sufia's date when the record was saved in the system (DateTime)
* ~~`date_modified`, Sufia's last modification date (DateTime)~~
* ~~`create_date`, Fedora's internal date, should be equivalent to `date_uploaded` (DateTime) tracks to the existing created at date~~
* ~~`modified_date`, Fedora's internal date of last modification, applies to GenericWork _only_ (DateTime)~~
* `rights`, dropdown selection
*  `id`, the original NOID for the work, used in the url (fixed in #211)

## TODO

- [x] WorkVersion's published_date is a singular field and validated #140 
- [x] Migrating resource types to work types #148 
- [x] Create new date field for migrated creation dates #327
- [x] Migrate keywords to keyword #321
- [x] Migrate Published Date #330
- [x] Migrating multiple rights #331
- [x] Verify all Collection fields map the same as GenericWork #332

**Comment by awead** [comment]
Results:
Resource types are mapped 1:1 from SS3 to SS4 and will be used to populate the dropdown menu when creating new works. Multiple types will changed to one based on a mapping strategy.
