### ISSUE TITLE
Work Manager View

### ISSUE THREAD

**Issue by srerickson** [psu-stewardship/scholarsphere-4#207]
Currently, the range of activities involved in managing an individual work are initiated through the "Your ScholarSphere Deposits" Dashboard view. That view, which is based on a wire frame I made, lists all a user's works, all the versions associated with those works, and includes links to perform various actions. 

I think we need a separate page for managing an individual work: it will simplify the "dashboard" view and it also makes it possible for administrators and users to use the same interface for managing a work. (The dashboard page should just list works and link to the work manger page). 

The work manager page should include:
- A list of versions (potentially expand full changes between version)
- Button for creating new version for the work.
- Button for deleting draft version
- Button for deleting the work itself, if allowed (i.e. work includes no published versions). 
- Button for creating a DOI if the work doesn't have one
- Button for creating a DOI for a specific work version
- other convenience actions. 

- [x] #239 Complete UI Wireframes
- [x] #265 🚦Logic for Work Metadata 
- [ ] #150 Minting DOIs
- [ ] #238 Implementation
- [ ] #29 My Dashboard Page
- [ ] #274 Work View Validation on submit
- [ ] #277 ACLs UI component

@monksp

**Comment by monksp** [comment]
![work manager](https://user-images.githubusercontent.com/3210345/75351678-8214ae00-5876-11ea-8704-2e84d1cf58a6.png)
![doi variations](https://user-images.githubusercontent.com/3210345/75351681-84770800-5876-11ea-8e3b-742b3aec1d61.png)
![version variations](https://user-images.githubusercontent.com/3210345/75351683-84770800-5876-11ea-9960-377084afd13c.png)

Initial mockups attached.  There are a few more sections to sketch out, but I wanted to make sure everyone had time to look over what's already done.

One thing that occurred to me while doing this is that this should probably take the place of the "upload files -> add metadata -> click the button and publish" workflow for initial work creation.  It would give a unified feel to the process of creation and updates.  We'd probably want to add a little bit of chrome to the page for new works in that case, so that people would have something leading them through the process.

**Comment by monksp** [comment]
![Screen Shot 2020-03-11 at 11 32 13 AM](https://user-images.githubusercontent.com/3210345/76435111-fbd78c00-638c-11ea-8573-abd6918c5fad.png)
![Screen Shot 2020-03-11 at 11 32 28 AM](https://user-images.githubusercontent.com/3210345/76435123-fed27c80-638c-11ea-9bfc-83077938c892.png)
![Screen Shot 2020-03-11 at 11 32 47 AM](https://user-images.githubusercontent.com/3210345/76435139-02fe9a00-638d-11ea-91a1-c7486fd6fd78.png)
![Screen Shot 2020-03-11 at 11 33 02 AM](https://user-images.githubusercontent.com/3210345/76435150-05f98a80-638d-11ea-965e-cf6f128ad025.png)
![Screen Shot 2020-03-11 at 11 33 13 AM](https://user-images.githubusercontent.com/3210345/76435158-08f47b00-638d-11ea-96b3-473deeb0fb77.png)
![Screen Shot 2020-03-11 at 11 33 29 AM](https://user-images.githubusercontent.com/3210345/76435169-0b56d500-638d-11ea-9219-94b86bf8ec8f.png)
![Screen Shot 2020-03-11 at 11 33 44 AM](https://user-images.githubusercontent.com/3210345/76435184-0e51c580-638d-11ea-8c89-546ac5cad5e4.png)

New set of mockups.  This starts by redoing the work manager page slightly, primarily the file upload section, removing the thumbnails.  Per the conversation that @awead and I had, what the file list ultimately looks like might be a function of the upload library we're using more than anything else.  There's also two grey blocks in the upper right, which are just the version and doi sections from the initial mockups that I left off because there's already designs for them that didn't get touched.

The onboarding process is the main new thing.  Pretty straightforward, it works like a product tour when you open an app for the first time, popping up tooltips to guide a user through the initial stages.  In this case, it walks the user field to field for all of the things that are needed specifically to be able to save a draft.  Then, it'll pop up some informational tooltips on what's needed afterwards (more details in the screenshots).

**Comment by srerickson** [comment]
Some quick notes mostly for me to refer to later:

- The tooltips and the traffic light ux pattern are awesome!
- the metadata fields above the file area are precious real estate, and we need to discuss what goes there a bit more. I don't think subtitle is that important and visibility settings might be handled closer to the moment of publishing. (visibility can't change between versions. Does visibility need to be set to save a draft?). I would like to see a field for publication date added here.

**Comment by monksp** [comment]
Minor changes to some of the variations on the versioning block.  These are just the interactive ones, and the main thing is that the visibility switch has been moved here from the main part of the metadata section.  In the versions I didn't redo, which would be the ones where you're looking at a published version, not a draft, the lightswitch should just get replaced with some wording to the "Publicly available" "Restricted to PSU" effect.

![Screen Shot 2020-03-24 at 9 45 39 AM](https://user-images.githubusercontent.com/3210345/77432520-8cae5e80-6db4-11ea-9a3f-e04f86c11e59.png)
![Screen Shot 2020-03-24 at 9 45 28 AM](https://user-images.githubusercontent.com/3210345/77432524-8d46f500-6db4-11ea-8202-abcff602d0e8.png)

**Comment by monksp** [comment]
These are just quick workups of the "Your Deposits" page, after our discussions about looking at the entire process from earlier.  Definitely nothing final here, but just to give an idea of the whole lifecycle of a work.  There's a new work creation form at the top (with multiple versions dependent on state), and "New Version" and "Continue Working" buttons in the individual work boxes at the bottom, which would deposit the user in the Work Manager page.

The main idea here is that those two things would put the user into the Work Manager at different states.

- The new work form would start the user off with the full onboarding tooltip process, starting at the tooltip _after_ the title, because the title would be filled out on this form.
- The new version form would be the full onboarding process, but with different wording in the tooltips.  So instead of prompting for inputs, it would be reminding you to make sure things are correct.  "Make sure the title is stil correct to reflect the changes you're making" vs "First, we need a title" etc.
- The continue button wouldn't do any onboarding at all, with the assumption that the user had just recently gone through it, so would rely on the traffic light and its messaging to continue communicating with the user.

![Screen Shot 2020-03-24 at 9 28 24 AM](https://user-images.githubusercontent.com/3210345/77432799-eb73d800-6db4-11ea-9d91-a4e1910a6727.png)
![Screen Shot 2020-03-24 at 9 28 42 AM](https://user-images.githubusercontent.com/3210345/77432808-ee6ec880-6db4-11ea-8655-f9bacb95d39e.png)
![Screen Shot 2020-03-24 at 9 28 56 AM](https://user-images.githubusercontent.com/3210345/77432827-f464a980-6db4-11ea-86d2-73d79f7c1b5f.png)

**Comment by monksp** [comment]
Just a new overview of the work manager to reflect that the PSU restricted lightswitch isn't there anymore.

![Screen Shot 2020-03-24 at 9 29 29 AM](https://user-images.githubusercontent.com/3210345/77433458-c6339980-6db5-11ea-9dc2-2bb61e10252d.png)

**Comment by monksp** [comment]
Final part of the publishing process.  Pop up an interruption, itemizing out all of the stuff that the user should double-check, then provide some messaging afterwards that they have to deliberately acknowledge.

![Screen Shot 2020-03-24 at 9 30 29 AM](https://user-images.githubusercontent.com/3210345/77433639-ff6c0980-6db5-11ea-9388-93715918a37f.png)
![Screen Shot 2020-03-24 at 9 30 47 AM](https://user-images.githubusercontent.com/3210345/77433652-0266fa00-6db6-11ea-909d-cba09a052acd.png)
