### ISSUE TITLE
Implement Collections

### ISSUE THREAD

**Issue by awead** [psu-stewardship/scholarsphere-4#213]
Collections hold an arbitrary number of works and contain the same metadata as works as well. For the purposes of Scholarsphere 4, collections will include the same features as the do in Scholarsphere 3. (see #91)

## WDLL
* collection display page
* collections in search results
* pages for creating and editing collections, including adding/removing works

- [x] #91 Collections Functionality -- this is really a duplicate I think of this ticket but making sure we recognize it
- [x] #253 Create Collections Page
- [x] #254 Edit Collections Page
- [x] #255 Collections Model 
- [x] #256 Collections appear in Dashboard page
- [x] #271 Index Collections
- [x] #272 Legacy Collection IDs
- [x] #273 DOI for Collections
- [x] #275 Default Ordering of Collections (?)
- [x] #284 Collection View Page

**Comment by srerickson** [comment]
In case this comes up: you should be able to add an existing work version to a collection without creating a new version.

Some features I'd like to have down the road, but not necessary for launch:
- An ACL (?) that allows anyone to add works to a collection and only allows removing works you've added;
- The ability to configure a collection's ordering logic (publication date, alphabetical by title, custom, etc).
