### ISSUE TITLE
Work Edit Actions UI Components

### ISSUE THREAD

**Issue by srerickson** [psu-stewardship/scholarsphere-4#338]
We need a UI component providing users with the ability to initiate a variety of actions related to the management of their work. This component will likely appear on the work page for works the user can edit. (replaces #207).

## Edit actions for a work include:
- [x] Change Access Controls #277 
- [x] Create a DOI for the work if none exists (#150)
- [x] Changing visibility (toggle b/w Public & Penn State) (#601)
- [x] Setting Embargo (#621)
~~List versions, w/ actions for requesting withdrawal and deleting (if the draft)~~ #696 

*updated by seth 10/23*

**Comment by srerickson** [comment]
Instead of packing all this functionality into the drop down and modal UIs, it may be easier and more user friendly for the gear icon to be a link ("gear Work Settings") to a separate page where you can do all this stuff. 

I'm imagining something like this:
![Screenshot from 2020-10-23 14-22-03](https://user-images.githubusercontent.com/876323/97040147-8f845400-153b-11eb-9564-363e03021912.png)
