### ISSUE TITLE
DOI Integration

### ISSUE THREAD

**Issue by DanCoughlin** [psu-stewardship/scholarsphere-4#8]
Leaning towards having a DOI for a work not for each version of the work. If you would like to have a version to be attached, you can, but it is not the default (to have a version for each work).

## Related Tickets

- [x] Mapping Datacite DOI states to Scholarsphere work states #99
- [x] Add DOI fields to Work and WorkVersion #100
- [x] Mapping metadata to Datacite #101
- [x] Datacite client service #102
- [x] DOI Service #103
- [x] Implement aliases #186 
- [x] Sidekiq and Redis #104
- [x] DOI Job to run the DOI service #105 
- [ ] Mint DOIs for works and work versions (with UI) #150
- [ ] Map our work_type metadata field to DataCite's resourceTypeGeneral #576

**Comment by DanCoughlin** [comment]
We will initially code up the work that needs to be done to talk to the DOI service and mint the identifier. We will assign the DOI to the work and hold off on the versions.

**Comment by DanCoughlin** [comment]
We could improve existing synchronization between ScholarSphere and Datacite. If we update a title in ScholarSphere, then we should update the title in Datacite for example. We are going to want to integrate the workflow of ScholarSphere and drafting and publishing works and how that integrates with the Datacite work state. This part may be the second portion of ticket after getting scaffolding up and running to make sure the integration is there.

**Comment by awead** [comment]
## TODO
* draft vs. published DOIs
* migrating between the two

**Comment by whereismyjetpack** [comment]
events: ['publish', 'register', 'hide'] 

```Possible actions:

    publish - Triggers a state move from draft or registered to findable
    register - Triggers a state move from draft to registered
    hide - Triggers a state move from findable to registered```

published are the only findable types i believe. which begs the question, what are the differences between `registered` and `draft`

**Comment by DanCoughlin** [comment]
Draft DOI can be deleted, doesn't need a valid URL or valid metadata. It's basically a reservation, that can be promoted to published. A draft DOI is not indexed and searchable. To promote from draft to registered it will require a certain amount of metadata. You can hide a DOI or a DOI that is registered only, can be deleted.

DOI State Documentation:  https://support.datacite.org/docs/doi-states

We are only going to add DOIs when a user is explicitly requesting for a DOI. The draft status use case is a researcher creates a DOI for a data set on a paper that is submitted for publication. If the paper is published then promote the DOI to a published DOI, if the paper is not published the user may come back and delete the DOI.
